### ISSUE TITLE
BOM available?

### ISSUE THREAD

**Issue by FlorianO** [TomWhitwell/Voltages-Expander#1]
Hey, can you add a BOM to the repo?
I only have a PCB and a panel. :(

**Comment by aleesajade** [comment]
Were you missing the materials?

**Comment by FlorianO** [comment]
I got the board from someone who haden't the materials anymore.

**Comment by TomWhitwell** [comment]
Sorry for the delay

Qty | Value | Device | Parts | Description | Mouser
-- | -- | -- | -- | -- | --
8 | 50k | Illuminated Fader | GATE1, GATE2, GATE3, GATE4, GATE5, GATE6, GATE7, GATE8 | 20mm Alpha Illuminated Fader | 312-2045F-R50K
1 | 10k | 9mm pot | SCALE | 9 mm vertical pot, D shaft | 688-RK09K1130AH1
1 | 50k | 9mm pot | OFFSET | 9 mm vertical pot, D shaft | 652-PTV09A-4025FB503
2 | 100n | C-EU025-024X044 | C1, C2 | CAPACITOR | 594-K104K15X7RF5TH5
1 | TL074 | TL074 | IC1 | OP AMP | 595-TL074CN
1 |   | MA08-2 | GATES | PIN HEADER 2x8 | 649-67997-216HLF
1 | 78L09 |   | 78L1 | Positive VOLTAGE REGULATOR | 511-L78L09ACZ
6 | 10k | R-EU_0207/10 | R3, R4, R5, R6, R7, R8 | RESISTOR | 660-MF1/4DCT52A1002F
4 | 1k | R-EU_0207/10 | R1, R2, R9, R10 | RESISTOR | 660-MF1/4DCT52R1001F
1 | 10k | RN08 | RN1 | Resistor Network 9 pin, 8 resistors, bussed | 652-4609X-1LF-10K
1 | 2k | RN08 | RN2 | Resistor Network 9 pin, 8 resistors, bussed | 652-4609X-1LF-2K
3 | PJ-301B | PJ-301B | CLOCK_OUT, INVERT_OUT, MAIN_OUT | Sockets | Available from Erthenvar or Thonk
1 |   |   | 14 pin DIP socket |   | 649-DILB14P-223TLF
  |   |   |   |   |  

Qty	Value	Device	Parts	Description	Mouser 
8	50k	Illuminated Fader	GATE1, GATE2, GATE3, GATE4, GATE5, GATE6, GATE7, GATE8	20mm Alpha Illuminated Fader	312-2045F-R50K
1	10k	9mm pot	SCALE	9 mm vertical pot, D shaft	688-RK09K1130AH1
1	50k	9mm pot	OFFSET	9 mm vertical pot, D shaft	652-PTV09A-4025FB503
2	100n	C-EU025-024X044	C1, C2	CAPACITOR	594-K104K15X7RF5TH5
1	TL074	TL074	IC1	OP AMP	[595-TL074CN](https://uk.mouser.com/Search/ProductDetail.aspx?R=TL074CNvirtualkey59500000virtualkey595-TL074CN)
1		MA08-2	GATES	PIN HEADER 2x8	[649-67997-216HLF](https://uk.mouser.com/Search/ProductDetail.aspx?R=67997-216HLFvirtualkey64910000virtualkey649-67997-216HLF)
1	78L09		78L1	Positive VOLTAGE REGULATOR	511-L78L09ACZ
6	10k	R-EU_0207/10	R3, R4, R5, R6, R7, R8	RESISTOR	[660-MF1/4DCT52A1002F](https://uk.mouser.com/Search/ProductDetail.aspx?R=MF1%2f4DCT52A1002Fvirtualkey66000000virtualkey660-MF1%2f4DCT52A1002F)
4	1k	R-EU_0207/10	R1, R2, R9, R10	RESISTOR	[660-MF1/4DCT52R1001F](https://uk.mouser.com/Search/ProductDetail.aspx?R=MF1%2f4DCT52R1001Fvirtualkey66000000virtualkey660-MF1%2f4DCT52R1001F)
1	10k	RN08	RN1	Resistor Network 9 pin, 8 resistors, bussed	[652-4609X-1LF-10K](https://uk.mouser.com/Search/ProductDetail.aspx?R=4609X-101-103LFvirtualkey65210000virtualkey652-4609X-1LF-10K)
1	2k	RN08	RN2	Resistor Network 9 pin, 8 resistors, bussed	652-4609X-1LF-2K
3	PJ-301B	PJ-301B	CLOCK_OUT, INVERT_OUT, MAIN_OUT	Sockets	Available from Erthenvar or Thonk
1			14 pin DIP socket 		[649-DILB14P-223TLF](https://uk.mouser.com/Search/ProductDetail.aspx?R=DILB14P-223TLFvirtualkey64910000virtualkey649-DILB14P-223TLF)

**Comment by FlorianO** [comment]
Thank you so much. :)
